import React, { useState, useMemo, useRef, useCallback } from "react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../ui/table";
import { Input } from "../ui/input";
import { Button } from "../ui/button";
import { Checkbox } from "../ui/checkbox";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "../ui/dropdown-menu";
import { HoverCard, HoverCardTrigger, HoverCardContent } from "../ui/hover-card";
import { OverflowTooltip } from "./OverflowTooltip";
import { ColumnSelector, ColumnSelectorTrigger } from "./ColumnSelector";
import { Search, X, SlidersHorizontal, MoreHorizontal, Eye, Pencil, Trash2, Copy, ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight, AlignJustify, List, Check, ChevronDown, GripVertical, Mail, Phone, Building2, Plus } from "lucide-react";
import { usePersonLightbox } from "../vendors/PersonAvatarLightbox";
import { getAvatarTint } from "../../utils/avatarTints";

/* ─── External module URL (fixed) ─── */
const SO_MODULE_URL = "https://joyride-sync.lovable.app/sales-orders";

type ColKey = "so_no" | "quote_no" | "customer" | "status" | "poc" | "sales_rep" | "order_value" | "invoiced" | "payments" | "order_date" | "ship_by" | "delivery_date" | "created_on" | "created_by" | "priority" | "warehouse";
interface ColDef { key: ColKey; label: string; defaultWidth: number; minWidth: number; sticky?: "left"; align?: "right"; locked?: boolean }

const COLUMN_DEFS: ColDef[] = [
  { key: "so_no", label: "Sales Order #", defaultWidth: 180, minWidth: 130, sticky: "left", locked: true },
  { key: "quote_no", label: "Quote #", defaultWidth: 150, minWidth: 100 },
  { key: "customer", label: "Customer Name", defaultWidth: 230, minWidth: 160 },
  { key: "status", label: "Order Status", defaultWidth: 165, minWidth: 120 },
  { key: "poc", label: "Point of Contact", defaultWidth: 175, minWidth: 130 },
  { key: "sales_rep", label: "Sales Rep", defaultWidth: 170, minWidth: 130 },
  { key: "order_value", label: "Order Value", defaultWidth: 130, minWidth: 100, align: "right" },
  { key: "invoiced", label: "Invoiced Amount", defaultWidth: 145, minWidth: 100, align: "right" },
  { key: "payments", label: "Payments Made", defaultWidth: 140, minWidth: 100, align: "right" },
  { key: "order_date", label: "Order Date", defaultWidth: 115, minWidth: 90 },
  { key: "ship_by", label: "Ship By", defaultWidth: 115, minWidth: 90 },
  { key: "delivery_date", label: "Delivery Date", defaultWidth: 120, minWidth: 90 },
  { key: "created_on", label: "Created On", defaultWidth: 115, minWidth: 90 },
  { key: "created_by", label: "Created By", defaultWidth: 170, minWidth: 130 },
  { key: "priority", label: "Priority", defaultWidth: 110, minWidth: 80 },
  { key: "warehouse", label: "Warehouse", defaultWidth: 155, minWidth: 100 },
];
const cDef = (key: string) => COLUMN_DEFS.find(c => c.key === key)!;
const DEFAULT_VIS: ColKey[] = ["so_no", "quote_no", "customer", "status", "poc", "sales_rep", "order_value", "invoiced", "payments"];

function getPhoto(name: string): string { let h = 0; for (let i = 0; i < name.length; i++) h = name.charCodeAt(i) + ((h << 5) - h); const a = Math.abs(h); return `https://randomuser.me/api/portraits/${a % 2 === 0 ? "men" : "women"}/${(a % 99) + 1}.jpg`; }

const SO_DATA = [
  { id: "SO-000-000-000", version: "v1", quoteNo: "Q-000-100-001", customer: "Metro City Fire & Rescue", customerCode: "MC", status: "Draft", poc: "Meredith", pocExtra: 0, pocRole: "Account Manager", pocEmail: "meredith@metrocity.gov", pocDept: "Procurement", pocPhone: "(312) 555-0100", salesRep: "Sarah Lindquist", srCode: "SL", srRole: "Sales Director", srEmail: "sarah.l@company.com", srDept: "Sales", srPhone: "(555) 100-2000", orderValue: 206232, invoiced: null as number | null, payments: null as number | null, orderDate: "01/10/2025", shipBy: "03/10/2025", deliveryDate: "04/10/2025", createdOn: "01/07/2025", createdBy: "Emily Chen", cbCode: "EC", cbRole: "Operations Analyst", cbEmail: "emily.c@company.com", cbDept: "Operations", cbPhone: "(555) 200-3000", priority: "Low", warehouse: "Main Warehouse" },
  { id: "SO-000-000-001", version: "v2", quoteNo: "—", customer: "Tri-County EMS Authority", customerCode: "TE", status: "Draft", poc: "Toby", pocExtra: 0, pocRole: "Fleet Manager", pocEmail: "toby@tricounty.org", pocDept: "Fleet", pocPhone: "(555) 111-2222", salesRep: "Michael Tran", srCode: "MT", srRole: "Account Exec", srEmail: "michael.t@company.com", srDept: "Sales", srPhone: "(555) 300-4000", orderValue: 162594, invoiced: null, payments: null, orderDate: "02/11/2025", shipBy: "04/11/2025", deliveryDate: "05/11/2025", createdOn: "02/08/2025", createdBy: "Adrian User", cbCode: "AU", cbRole: "Admin", cbEmail: "adrian@company.com", cbDept: "Admin", cbPhone: "(555) 400-5000", priority: "Standard", warehouse: "Main Warehouse" },
  { id: "SO-000-000-002", version: "v3", quoteNo: "Q-000-102-007", customer: "Lakewood Community Hospital", customerCode: "LC", status: "Pending Review", poc: "Robert", pocExtra: 1, pocRole: "Purchasing Dir", pocEmail: "robert@lakewood.org", pocDept: "Purchasing", pocPhone: "(555) 222-3333", salesRep: "Emily Rios", srCode: "ER", srRole: "Sales Rep", srEmail: "emily.r@company.com", srDept: "Sales", srPhone: "(555) 500-6000", orderValue: 77981, invoiced: 38991, payments: null, orderDate: "03/12/2025", shipBy: "05/12/2025", deliveryDate: "06/12/2025", createdOn: "03/09/2025", createdBy: "System Import", cbCode: "SI", cbRole: "System", cbEmail: "", cbDept: "", cbPhone: "", priority: "High", warehouse: "Main Warehouse" },
  { id: "SO-000-000-003", version: "v4", quoteNo: "Q-000-103-010", customer: "Pinecrest Volunteer Fire", customerCode: "PV", status: "Cleared by Ops", poc: "Ryan", pocExtra: 0, pocRole: "Chief", pocEmail: "ryan@pinecrest.org", pocDept: "Command", pocPhone: "(555) 333-4444", salesRep: "David Kowalski", srCode: "DK", srRole: "Senior AE", srEmail: "david.k@company.com", srDept: "Sales", srPhone: "(555) 600-7000", orderValue: 74493, invoiced: null, payments: 18623, orderDate: "04/13/2025", shipBy: "06/13/2025", deliveryDate: "07/13/2025", createdOn: "04/10/2025", createdBy: "Marcus Taylor", cbCode: "MT", cbRole: "Ops Manager", cbEmail: "marcus@company.com", cbDept: "Operations", cbPhone: "(555) 700-8000", priority: "Low", warehouse: "Main Warehouse" },
  { id: "SO-000-000-004", version: "v1", quoteNo: "—", customer: "Summit Regional Medical", customerCode: "SR", status: "Cleared by Ops", poc: "Kevin", pocExtra: 1, pocRole: "Supply Mgr", pocEmail: "kevin@summit.org", pocDept: "Supply Chain", pocPhone: "(555) 444-5555", salesRep: "Jessica Mbeki", srCode: "JM", srRole: "Sales Lead", srEmail: "jessica.m@company.com", srDept: "Sales", srPhone: "(555) 800-9000", orderValue: 174101, invoiced: 174102, payments: null, orderDate: "05/14/2025", shipBy: "07/14/2025", deliveryDate: "08/14/2025", createdOn: "05/11/2025", createdBy: "Adrian User", cbCode: "AU", cbRole: "Admin", cbEmail: "adrian@company.com", cbDept: "Admin", cbPhone: "(555) 400-5000", priority: "Standard", warehouse: "East Hub" },
  { id: "SO-000-000-005", version: "v2", quoteNo: "Q-000-105-016", customer: "Eagle County Sheriff's Office", customerCode: "EC", status: "Partially Shipped", poc: "Pam", pocExtra: 0, pocRole: "Procurement", pocEmail: "pam@eagle.gov", pocDept: "Admin", pocPhone: "(555) 555-6666", salesRep: "Robert Navarro", srCode: "RN", srRole: "Territory Rep", srEmail: "robert.n@company.com", srDept: "Sales", srPhone: "(555) 900-0001", orderValue: 48438, invoiced: null, payments: 24219, orderDate: "06/15/2025", shipBy: "08/15/2025", deliveryDate: "09/15/2025", createdOn: "06/12/2025", createdBy: "David Park", cbCode: "DP", cbRole: "Analyst", cbEmail: "david.p@company.com", cbDept: "Analytics", cbPhone: "(555) 000-1111", priority: "High", warehouse: "Main Warehouse" },
  { id: "SO-000-000-006", version: "v1", quoteNo: "Q-000-106-019", customer: "Pacific Northwest Ambulance", customerCode: "PN", status: "Shipped", poc: "Holly", pocExtra: 1, pocRole: "Ops Director", pocEmail: "holly@pnw-amb.com", pocDept: "Operations", pocPhone: "(555) 666-7777", salesRep: "Amanda Chen", srCode: "AC", srRole: "Account Mgr", srEmail: "amanda.c@company.com", srDept: "Sales", srPhone: "(555) 111-2223", orderValue: 66042, invoiced: 33021, payments: 16511, orderDate: "07/16/2025", shipBy: "10/16/2025", deliveryDate: "10/16/2025", createdOn: "07/13/2025", createdBy: "Emily Chen", cbCode: "EC", cbRole: "Operations Analyst", cbEmail: "emily.c@company.com", cbDept: "Operations", cbPhone: "(555) 200-3000", priority: "Low", warehouse: "West Depot" },
  { id: "SO-000-000-007", version: "v4", quoteNo: "—", customer: "Riverside Utility District", customerCode: "RU", status: "Shipped", poc: "Creed", pocExtra: 0, pocRole: "Facilities Mgr", pocEmail: "creed@riverside.gov", pocDept: "Facilities", pocPhone: "(555) 777-8888", salesRep: "James Hatfield", srCode: "JH", srRole: "Sales Rep", srEmail: "james.h@company.com", srDept: "Sales", srPhone: "(555) 222-3334", orderValue: 89370, invoiced: null, payments: null, orderDate: "08/17/2025", shipBy: "10/17/2025", deliveryDate: "11/17/2025", createdOn: "08/14/2025", createdBy: "Emily Chen", cbCode: "EC", cbRole: "Operations Analyst", cbEmail: "emily.c@company.com", cbDept: "Operations", cbPhone: "(555) 200-3000", priority: "Standard", warehouse: "Main Warehouse" },
  { id: "SO-000-000-008", version: "v1", quoteNo: "Q-000-108-025", customer: "Heartland Air Ambulance", customerCode: "HA", status: "Shipped", poc: "Meredith", pocExtra: 1, pocRole: "Account Manager", pocEmail: "meredith@heartland.com", pocDept: "Accounts", pocPhone: "(555) 888-9999", salesRep: "Sarah Lindquist", srCode: "SL", srRole: "Sales Director", srEmail: "sarah.l@company.com", srDept: "Sales", srPhone: "(555) 100-2000", orderValue: 300672, invoiced: 300672, payments: null, orderDate: "09/18/2025", shipBy: "11/18/2025", deliveryDate: "12/18/2025", createdOn: "09/15/2025", createdBy: "System Import", cbCode: "SI", cbRole: "System", cbEmail: "", cbDept: "", cbPhone: "", priority: "High", warehouse: "Main Warehouse" },
  { id: "SO-000-000-009", version: "v2", quoteNo: "Q-000-109-028", customer: "Great Plains Fire Protection", customerCode: "GP", status: "Cancelled", poc: "Ryan", pocExtra: 0, pocRole: "Captain", pocEmail: "ryan@gpfire.org", pocDept: "Command", pocPhone: "(555) 999-0000", salesRep: "Michael Tran", srCode: "MT", srRole: "Account Exec", srEmail: "michael.t@company.com", srDept: "Sales", srPhone: "(555) 300-4000", orderValue: 344039, invoiced: null, payments: 86010, orderDate: "10/19/2025", shipBy: "12/19/2025", deliveryDate: "12/19/2025", createdOn: "10/16/2025", createdBy: "Marcus Taylor", cbCode: "MT", cbRole: "Ops Manager", cbEmail: "marcus@company.com", cbDept: "Operations", cbPhone: "(555) 700-8000", priority: "Low", warehouse: "East Hub" },
  { id: "SO-000-000-010", version: "v3", quoteNo: "—", customer: "Coastal Search & Rescue", customerCode: "CS", status: "Cleared by Ops", poc: "Kevin", pocExtra: 0, pocRole: "Logistics", pocEmail: "kevin@coastal.org", pocDept: "Logistics", pocPhone: "(555) 000-1112", salesRep: "Emily Rios", srCode: "ER", srRole: "Sales Rep", srEmail: "emily.r@company.com", srDept: "Sales", srPhone: "(555) 500-6000", orderValue: 150012, invoiced: 75006, payments: 75006, orderDate: "11/20/2025", shipBy: "12/20/2025", deliveryDate: "12/20/2025", createdOn: "11/17/2025", createdBy: "James Rodriguez", cbCode: "JR", cbRole: "Warehouse Lead", cbEmail: "james.r@company.com", cbDept: "Warehouse", cbPhone: "(555) 333-4445", priority: "Standard", warehouse: "Main Warehouse" },
  { id: "SO-000-000-011", version: "v4", quoteNo: "Q-000-111-034", customer: "Valley Health Systems", customerCode: "VH", status: "Cleared by Ops", poc: "Robert", pocExtra: 1, pocRole: "Purchasing", pocEmail: "robert@valley.org", pocDept: "Purchasing", pocPhone: "(555) 111-2224", salesRep: "David Kowalski", srCode: "DK", srRole: "Senior AE", srEmail: "david.k@company.com", srDept: "Sales", srPhone: "(555) 600-7000", orderValue: 162594, invoiced: null, payments: null, orderDate: "12/21/2025", shipBy: "12/21/2025", deliveryDate: "12/21/2025", createdOn: "12/18/2025", createdBy: "Emily Chen", cbCode: "EC", cbRole: "Operations Analyst", cbEmail: "emily.c@company.com", cbDept: "Operations", cbPhone: "(555) 200-3000", priority: "High", warehouse: "Main Warehouse" },
  { id: "SO-000-000-012", version: "v1", quoteNo: "Q-000-112-037", customer: "Northern Plains Medical", customerCode: "NP", status: "Partially Shipped", poc: "Holly", pocExtra: 0, pocRole: "Ops Director", pocEmail: "holly@np-med.com", pocDept: "Operations", pocPhone: "(555) 222-3335", salesRep: "Jessica Mbeki", srCode: "JM", srRole: "Sales Lead", srEmail: "jessica.m@company.com", srDept: "Sales", srPhone: "(555) 800-9000", orderValue: 74191, invoiced: 74190, payments: 18548, orderDate: "01/22/2025", shipBy: "03/22/2025", deliveryDate: "04/22/2025", createdOn: "01/19/2025", createdBy: "Emily Chen", cbCode: "EC", cbRole: "Operations Analyst", cbEmail: "emily.c@company.com", cbDept: "Operations", cbPhone: "(555) 200-3000", priority: "Low", warehouse: "Main Warehouse" },
];

const STATUS_STYLES: Record<string, { bg: string; text: string; border: string }> = { "Draft": { bg: "#F1F5F9", text: "#475569", border: "#CBD5E1" }, "Pending Review": { bg: "#FFFBEB", text: "#92400E", border: "#FDE68A" }, "Cleared by Ops": { bg: "#ECFDF5", text: "#065F46", border: "#A7F3D0" }, "Partially Shipped": { bg: "#EFF6FF", text: "#1E40AF", border: "#BFDBFE" }, "Shipped": { bg: "#F0FDFA", text: "#115E59", border: "#99F6E4" }, "Cancelled": { bg: "#FEF2F2", text: "#991B1B", border: "#FECACA" } };
const PRIORITY_STYLES: Record<string, { bg: string; text: string; border: string }> = { "Low": { bg: "#ECFDF5", text: "#065F46", border: "#A7F3D0" }, "Standard": { bg: "#FFFBEB", text: "#92400E", border: "#FDE68A" }, "High": { bg: "#FEF2F2", text: "#991B1B", border: "#FECACA" } };
const FILTER_TABS = [{ key: "all", label: "Show All" }, { key: "Draft", label: "Draft" }, { key: "Pending Review", label: "Pending Review" }, { key: "Cleared by Ops", label: "Cleared by Ops" }, { key: "Partially Shipped", label: "Partially Shipped" }, { key: "Shipped", label: "Shipped" }, { key: "Cancelled", label: "Cancelled" }];

const CHECKBOX_W = 40; const ACTIONS_W = 60; const MIN_COL_W = 80;
const fmt = (n: number | null) => n == null ? "—" : `$${n.toLocaleString()}`;

function PersonHoverCard({ name, role, email, dept, phone, children }: { name: string; role: string; email: string; dept: string; phone: string; children: React.ReactNode }) {
  const tint = getAvatarTint(name); const photo = getPhoto(name);
  return (<HoverCard><HoverCardTrigger asChild>{children}</HoverCardTrigger><HoverCardContent side="bottom" align="start" className="w-[280px] p-0 rounded-xl border-0 shadow-[0_8px_30px_rgba(0,0,0,0.12)] overflow-hidden" onClick={(e: React.MouseEvent) => e.stopPropagation()}><div className="bg-gradient-to-br from-[#1E293B] to-[#334155] px-4 py-3 relative overflow-hidden"><div className="absolute -top-4 -right-4 w-20 h-20 rounded-full bg-white/[0.04]" /><div className="flex items-center gap-3 relative"><div className="w-11 h-11 rounded-full overflow-hidden border-2 border-white/20 shrink-0" style={{ backgroundColor: tint.bg }}><img src={photo} alt="" className="w-full h-full object-cover" onError={(e) => { (e.target as HTMLImageElement).style.display = "none"; }} /></div><div className="min-w-0"><p className="text-[14px] text-white truncate" style={{ fontWeight: 600 }}>{name}</p><p className="text-[11px] text-[#94A3B8] truncate">{role}</p></div></div></div><div className="bg-white px-4 py-3 space-y-2">{email && <div className="flex items-center gap-2.5 text-[12px] text-[#334155]"><Mail className="w-3.5 h-3.5 text-[#94A3B8] shrink-0" /><span className="truncate">{email}</span></div>}{dept && <div className="flex items-center gap-2.5 text-[12px] text-[#334155]"><Building2 className="w-3.5 h-3.5 text-[#94A3B8] shrink-0" /><span>{dept}</span></div>}{phone && <div className="flex items-center gap-2.5 text-[12px] text-[#334155]"><Phone className="w-3.5 h-3.5 text-[#94A3B8] shrink-0" /><span>{phone}</span></div>}</div></HoverCardContent></HoverCard>);
}

export function SalesOrdersTable() {
  const { openLightbox } = usePersonLightbox();
  const [search, setSearch] = useState(""); const [statusFilter, setStatusFilter] = useState("all"); const [density, setDensity] = useState<"condensed" | "comfort">("condensed");
  const [columnVisibility, setColumnVisibility] = useState<Record<string, boolean>>(() => { const v: Record<string, boolean> = {}; COLUMN_DEFS.forEach(c => { v[c.key] = DEFAULT_VIS.includes(c.key); }); return v; });
  const [columnOrder, setColumnOrder] = useState<ColKey[]>(COLUMN_DEFS.map(c => c.key)); const [columnWidths, setColumnWidths] = useState<Record<string, number>>({}); const [selectedRows, setSelectedRows] = useState<Set<string>>(new Set());
  const [isResizing, setIsResizing] = useState(false); const [resizingColumnKey, setResizingColumnKey] = useState<string | null>(null); const [draggingColumnKey, setDraggingColumnKey] = useState<string | null>(null); const [columnDrawerOpen, setColumnDrawerOpen] = useState(false);
  const resizeRef = useRef<{ columnKey: string; startX: number; startWidth: number } | null>(null); const colDragRef = useRef<{ columnKey: string; startX: number; startY: number; isDragging: boolean; lastSwapTime: number } | null>(null); const suppressNextClickRef = useRef(false); const ghostElRef = useRef<HTMLDivElement>(null);

  const toggleColVis = (k: ColKey) => setColumnVisibility(prev => ({ ...prev, [k]: !prev[k] }));
  const visibleColumns = useMemo(() => columnOrder.filter(k => columnVisibility[k] !== false), [columnOrder, columnVisibility]);
  const getWidth = (key: string) => columnWidths[key] ?? cDef(key).defaultWidth;
  const isRelaxed = density === "comfort"; const sz = isRelaxed ? "text-[13.5px]" : "text-sm";

  const handleResizeStart = useCallback((e: React.MouseEvent, ck: string) => { e.preventDefault(); e.stopPropagation(); resizeRef.current = { columnKey: ck, startX: e.clientX, startWidth: getWidth(ck) }; setIsResizing(true); setResizingColumnKey(ck); const onMove = (me: MouseEvent) => { if (!resizeRef.current) return; setColumnWidths(p => ({ ...p, [resizeRef.current!.columnKey]: Math.max(MIN_COL_W, resizeRef.current!.startWidth + (me.clientX - resizeRef.current!.startX)) })); }; const onUp = () => { resizeRef.current = null; setIsResizing(false); setResizingColumnKey(null); document.removeEventListener("mousemove", onMove); document.removeEventListener("mouseup", onUp); document.body.style.cursor = ""; document.body.style.userSelect = ""; }; document.addEventListener("mousemove", onMove); document.addEventListener("mouseup", onUp); document.body.style.cursor = "col-resize"; document.body.style.userSelect = "none"; }, [columnWidths]);

  const handleHeaderMouseDown = useCallback((e: React.MouseEvent, ck: string) => { if (cDef(ck).locked || isResizing || e.button !== 0) return; colDragRef.current = { columnKey: ck, startX: e.clientX, startY: e.clientY, isDragging: false, lastSwapTime: 0 }; const onMove = (me: MouseEvent) => { if (!colDragRef.current) return; if (!colDragRef.current.isDragging) { if (Math.sqrt((me.clientX - colDragRef.current.startX) ** 2 + (me.clientY - colDragRef.current.startY) ** 2) < 5) return; colDragRef.current.isDragging = true; document.body.style.userSelect = "none"; document.body.style.cursor = "grabbing"; setDraggingColumnKey(colDragRef.current.columnKey); } const ghost = ghostElRef.current; if (ghost) ghost.style.transform = `translate(${me.clientX}px, ${me.clientY}px)`; const now = performance.now(); if (now - colDragRef.current.lastSwapTime < 60) return; const dTh = document.querySelector<HTMLElement>(`th[data-col-drag-key="${colDragRef.current.columnKey}"]`); if (!dTh) return; const dr = dTh.getBoundingClientRect(); if (me.clientX >= dr.left && me.clientX <= dr.right) return; document.querySelectorAll<HTMLElement>("th[data-col-drag-key]").forEach(th => { const r = th.getBoundingClientRect(); if (me.clientX < r.left || me.clientX > r.right) return; const k = th.getAttribute("data-col-drag-key"); if (!k || k === colDragRef.current!.columnKey || cDef(k as ColKey)?.locked) return; setColumnOrder(p => { const si = p.indexOf(colDragRef.current!.columnKey as ColKey); const ti = p.indexOf(k as ColKey); if (si === -1 || ti === -1 || si === ti) return p; const n = [...p]; n.splice(si, 1); n.splice(ti, 0, colDragRef.current!.columnKey as ColKey); return n; }); colDragRef.current!.lastSwapTime = now; }); }; const onUp = () => { document.removeEventListener("mousemove", onMove); document.removeEventListener("mouseup", onUp); document.body.style.userSelect = ""; document.body.style.cursor = ""; if (colDragRef.current?.isDragging) { suppressNextClickRef.current = true; requestAnimationFrame(() => { suppressNextClickRef.current = false; }); } colDragRef.current = null; setDraggingColumnKey(null); }; document.addEventListener("mousemove", onMove); document.addEventListener("mouseup", onUp); }, [isResizing]);

  const { stickyOffsets, lastStickyKey } = useMemo(() => { const sc = visibleColumns.filter(k => cDef(k).sticky === "left"); const o: Record<string, number> = {}; let l = CHECKBOX_W; for (const k of sc) { o[k] = l; l += getWidth(k); } return { stickyOffsets: o, lastStickyKey: sc[sc.length - 1] || null }; }, [visibleColumns, columnWidths]);
  const filtered = useMemo(() => { let r = SO_DATA; if (statusFilter !== "all") r = r.filter(x => x.status === statusFilter); if (search) { const q = search.toLowerCase(); r = r.filter(x => x.id.toLowerCase().includes(q) || x.customer.toLowerCase().includes(q) || x.salesRep.toLowerCase().includes(q)); } return r; }, [search, statusFilter]);
  const filterCounts = useMemo(() => { const c: Record<string, number> = { all: SO_DATA.length }; SO_DATA.forEach(r => { c[r.status] = (c[r.status] || 0) + 1; }); return c; }, []);
  const totalW = CHECKBOX_W + visibleColumns.reduce((s, k) => s + getWidth(k), 0) + ACTIONS_W;
  const allSel = filtered.length > 0 && filtered.every(r => selectedRows.has(r.id)); const someSel = filtered.some(r => selectedRows.has(r.id));

  const renderCell = (so: typeof SO_DATA[0], key: ColKey) => {
    const tint = getAvatarTint(so.customer);
    switch (key) {
      case "so_no": return (<div className="flex items-center gap-2"><span className="text-[10px] px-1.5 py-0.5 rounded bg-[#F1F5F9] text-[#64748B]" style={{ fontWeight: 600 }}>{so.version}</span><span className={`${sz} text-[#0A77FF] cursor-pointer hover:underline`} style={{ fontWeight: 500 }}>{so.id}</span></div>);
      case "quote_no": return <span className={`${sz} text-[#64748B]`}>{so.quoteNo}</span>;
      case "customer": return (<div className={`flex items-center ${isRelaxed ? "gap-3" : "gap-2.5"}`}><div className={`${isRelaxed ? "w-8 h-8" : "w-7 h-7"} rounded-lg flex items-center justify-center shrink-0 text-[9px]`} style={{ backgroundColor: tint.bg, color: tint.fg, fontWeight: 700 }}>{so.customerCode}</div><span className={`${sz} truncate`} style={{ fontWeight: 500, color: "#1E293B" }}>{so.customer}</span></div>);
      case "status": { const ss = STATUS_STYLES[so.status] || STATUS_STYLES.Draft; return <span className="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs whitespace-nowrap" style={{ fontWeight: 500, backgroundColor: ss.bg, color: ss.text, borderColor: ss.border }}>{so.status}</span>; }
      case "poc": return (
        <div className="flex items-center gap-1">
          <PersonHoverCard name={so.poc} role={so.pocRole} email={so.pocEmail} dept={so.pocDept} phone={so.pocPhone}>
            <span className={`${sz} text-[#334155] cursor-pointer hover:text-[#0A77FF] transition-colors`}>{so.poc}</span>
          </PersonHoverCard>
          {so.pocExtra > 0 && (
            <OverflowTooltip category="Contacts" items={[{ id: `${so.id}-poc-extra`, name: `${so.poc} (additional)`, subtitle: "Point of Contact" }]}>
              <span className="text-[11px] shrink-0 cursor-default leading-none" style={{ fontWeight: 600, color: "#085FCC" }}>+{so.pocExtra} more</span>
            </OverflowTooltip>
          )}
        </div>
      );
      case "sales_rep": return (<PersonHoverCard name={so.salesRep} role={so.srRole} email={so.srEmail} dept={so.srDept} phone={so.srPhone}><div className={`flex items-center ${isRelaxed ? "gap-2.5" : "gap-2"} cursor-pointer`}><div className={`${isRelaxed ? "w-7 h-7" : "w-6 h-6"} rounded-full shrink-0 overflow-hidden`} style={{ backgroundColor: getAvatarTint(so.salesRep).bg }}><img src={getPhoto(so.salesRep)} alt="" className="w-full h-full object-cover" onError={(e) => { (e.target as HTMLImageElement).style.display = "none"; }} /></div><span className={`${sz} text-[#334155] truncate`}>{so.salesRep}</span></div></PersonHoverCard>);
      case "order_value": return <span className={sz} style={{ fontWeight: 500 }}>{fmt(so.orderValue)}</span>;
      case "invoiced": return <span className={`${sz} text-[#64748B]`}>{fmt(so.invoiced)}</span>;
      case "payments": return <span className={`${sz} text-[#64748B]`}>{fmt(so.payments)}</span>;
      case "order_date": return <span className={`${sz} text-[#64748B]`}>{so.orderDate}</span>;
      case "ship_by": return <span className={`${sz} text-[#64748B]`}>{so.shipBy}</span>;
      case "delivery_date": return <span className={`${sz} text-[#64748B]`}>{so.deliveryDate}</span>;
      case "created_on": return <span className={`${sz} text-[#64748B]`}>{so.createdOn}</span>;
      case "created_by": return (<PersonHoverCard name={so.createdBy} role={so.cbRole} email={so.cbEmail} dept={so.cbDept} phone={so.cbPhone}><div className={`flex items-center ${isRelaxed ? "gap-2.5" : "gap-2"} cursor-pointer`}><div className={`${isRelaxed ? "w-7 h-7" : "w-6 h-6"} rounded-full shrink-0 overflow-hidden`} style={{ backgroundColor: getAvatarTint(so.createdBy).bg }}><img src={getPhoto(so.createdBy)} alt="" className="w-full h-full object-cover" onError={(e) => { (e.target as HTMLImageElement).style.display = "none"; }} /></div><span className={`${sz} text-[#334155] truncate`} style={{ fontWeight: 500 }}>{so.createdBy}</span></div></PersonHoverCard>);
      case "priority": { const ps = PRIORITY_STYLES[so.priority] || PRIORITY_STYLES.Low; return <span className="inline-flex items-center rounded-full border px-2 py-0.5 text-[10px] whitespace-nowrap" style={{ fontWeight: 500, backgroundColor: ps.bg, color: ps.text, borderColor: ps.border }}>{so.priority}</span>; }
      case "warehouse": return <span className={`${sz} text-[#64748B] truncate block`}>{so.warehouse}</span>;
      default: return <span>—</span>;
    }
  };

  return (
    <div className="border border-border rounded-xl bg-card overflow-clip flex flex-1 min-h-[calc(100vh-260px)]">
      <div className="flex-1 min-w-0 flex flex-col overflow-clip">
      <div className="px-4 py-3 flex items-center gap-3 border-b border-[#F1F5F9] flex-wrap">
        <div className="relative flex-1 max-w-xs"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground/70 pointer-events-none" /><Input placeholder="Search orders..." value={search} onChange={(e) => setSearch(e.target.value)} className="pl-9 pr-8 h-9 text-sm bg-white border-border/80 shadow-sm placeholder:text-muted-foreground/50" />{search && <button onClick={() => setSearch("")} className="absolute right-2.5 top-1/2 -translate-y-1/2 p-0.5 rounded-full hover:bg-muted/60 text-muted-foreground hover:text-foreground transition-colors cursor-pointer"><X className="w-3.5 h-3.5" /></button>}</div>
        <button className="inline-flex items-center justify-center h-9 gap-1.5 px-3 rounded-lg border border-border/80 bg-white shadow-sm hover:bg-muted/50 transition-colors text-foreground cursor-pointer"><SlidersHorizontal className="w-3.5 h-3.5" /><span className="text-sm" style={{ fontWeight: 500 }}>Filters</span></button>
        <span className="text-sm tabular-nums ml-auto" style={{ fontWeight: 500 }}><span className="text-foreground">{filtered.length}</span><span className="text-muted-foreground/70"> orders</span></span>
        <DropdownMenu><DropdownMenuTrigger asChild><button className="inline-flex items-center justify-center h-9 gap-2 px-3 rounded-lg border border-border bg-white shadow-sm hover:bg-muted/40 transition-colors cursor-pointer">{density === "condensed" ? <AlignJustify className="w-[18px] h-[18px] text-muted-foreground/80" /> : <List className="w-[18px] h-[18px] text-muted-foreground/80" />}<span className="text-sm hidden md:inline" style={{ fontWeight: 500 }}>{density === "condensed" ? "Condensed" : "Comfort"}</span><ChevronDown className="w-3.5 h-3.5 text-muted-foreground/60" /></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-[200px] p-1.5">{(["condensed", "comfort"] as const).map(d => (<DropdownMenuItem key={d} className="flex items-center gap-3 py-2.5 px-3 cursor-pointer rounded-md" onSelect={() => setDensity(d)}>{d === "condensed" ? <AlignJustify className="w-5 h-5 text-muted-foreground shrink-0" /> : <List className="w-5 h-5 text-muted-foreground shrink-0" />}<span className="text-sm flex-1" style={{ fontWeight: 500 }}>{d === "condensed" ? "Condensed" : "Comfort"}</span>{density === d && <Check className="w-4 h-4 shrink-0" style={{ color: "#0A77FF" }} />}</DropdownMenuItem>))}</DropdownMenuContent></DropdownMenu>
        <ColumnSelectorTrigger visibleCount={visibleColumns.length} active={columnDrawerOpen} onClick={() => setColumnDrawerOpen(!columnDrawerOpen)} />
        <button
          type="button"
          onClick={() => window.open(`${SO_MODULE_URL}?action=create`, "_blank", "noopener")}
          className="inline-flex items-center gap-1.5 h-9 px-3.5 rounded-lg bg-[#0A77FF] hover:bg-[#0862D0] text-white text-sm shadow-sm transition-colors cursor-pointer"
          style={{ fontWeight: 600 }}
        >
          <Plus className="w-3.5 h-3.5" />
          <span className="hidden sm:inline">Create New Sales Order</span>
        </button>
      </div>
      <div className="px-4 py-2 flex items-center gap-2 overflow-x-auto scrollbar-hide">
        {FILTER_TABS.map(tab => { const a = statusFilter === tab.key; const c = filterCounts[tab.key] || 0; return (<button key={tab.key} onClick={() => setStatusFilter(tab.key)} className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full border text-xs transition-colors whitespace-nowrap shrink-0 cursor-pointer ${a ? "border-primary bg-[#EDF4FF]" : "border-border text-muted-foreground hover:bg-muted/60 hover:text-foreground"}`} style={{ fontWeight: a ? 500 : 400, color: a ? "#0A77FF" : undefined }}>{tab.label}<span className={`text-[10px] rounded-full px-1.5 py-px min-w-[18px] text-center ${a ? "bg-primary/10" : "bg-muted"}`} style={{ fontWeight: 600, color: a ? "#0A77FF" : "#475569" }}>{c}</span></button>); })}
      </div>
      <div className={`min-h-0 overflow-auto flex-1 ${isResizing || draggingColumnKey ? "select-none" : ""}`}>
        <Table style={{ tableLayout: "fixed", width: `max(${totalW}px, 100%)` }}>
          <TableHeader className="sticky top-0 z-20 bg-card"><TableRow className={`bg-muted/30 hover:bg-muted/30 ${density === "condensed" ? "[&>th]:h-8" : "[&>th]:h-9"}`}>
            <TableHead className="sticky left-0 z-20 bg-[#f8fafc]" style={{ width: CHECKBOX_W, minWidth: CHECKBOX_W, maxWidth: CHECKBOX_W, paddingLeft: 8, paddingRight: 0 }}><Checkbox checked={allSel ? true : someSel ? "indeterminate" : false} onCheckedChange={() => { if (allSel) setSelectedRows(new Set()); else setSelectedRows(new Set(filtered.map(r => r.id))); }} /></TableHead>
            {visibleColumns.map(key => { const def = cDef(key); const w = getWidth(key); const isS = def.sticky === "left"; const isLS = key === lastStickyKey; const isD = draggingColumnKey === key; const isDbl = !def.locked; return (
              <TableHead key={key} data-col-drag-key={key} onMouseDown={isDbl ? (e) => handleHeaderMouseDown(e, key) : undefined} onClickCapture={isDbl ? (e) => { if (suppressNextClickRef.current) { e.stopPropagation(); e.preventDefault(); } } : undefined} className={`whitespace-nowrap relative group/colheader ${isS ? "sticky z-20 bg-[#f8fafc]" : ""} ${def.align === "right" ? "text-right" : ""} ${isDbl ? "cursor-grab" : ""}`} style={{ width: w, minWidth: w, maxWidth: w, overflow: "hidden", ...(isS ? { left: stickyOffsets[key], ...(!isD && isLS ? { boxShadow: "inset -1px 0 0 0 rgba(0,0,0,0.08), 3px 0 6px -2px rgba(0,0,0,0.06)" } : {}) } : {}), ...(isD ? { background: "linear-gradient(180deg, rgba(10,119,255,0.08) 0%, rgba(10,119,255,0.03) 100%)" } : {}) }}>
                {isD && <div className="absolute top-0 left-0 right-0 h-[2px] rounded-b-full" style={{ backgroundColor: "#0A77FF" }} />}
                {isDbl && <GripVertical className={`absolute left-1 top-1/2 -translate-y-1/2 w-3 h-3 transition-opacity z-[5] pointer-events-none ${isD ? "opacity-100 text-primary" : "opacity-0 group-hover/colheader:opacity-100 text-muted-foreground/40"}`} />}
                <span className="text-[13px]">{def.label}</span>
                <div onMouseDown={(e) => { e.stopPropagation(); handleResizeStart(e, key); }} onClick={(e) => e.stopPropagation()} onDoubleClick={(e) => { e.stopPropagation(); setColumnWidths(p => ({ ...p, [key]: def.defaultWidth })); }} className="absolute right-0 top-0 bottom-0 w-[5px] cursor-col-resize z-10 group/resize" style={{ touchAction: "none" }}><div className={`absolute right-0 top-1 bottom-1 w-[2px] rounded-full transition-colors ${resizingColumnKey === key ? "bg-primary" : "bg-transparent group-hover/resize:bg-primary/40"}`} /></div>
              </TableHead>
            ); })}
            <TableHead className="whitespace-nowrap sticky right-0 z-20 bg-[#f8fafc] !pl-2 !pr-2" style={{ width: ACTIONS_W, minWidth: ACTIONS_W, maxWidth: ACTIONS_W, boxShadow: "inset 1px 0 0 0 rgba(0,0,0,0.08)" }}><span className="text-[13px]">Actions</span></TableHead>
          </TableRow></TableHeader>
          <TableBody>
            {filtered.length === 0 ? (<TableRow><TableCell colSpan={visibleColumns.length + 2} className="text-center py-12 text-muted-foreground">No sales orders found.</TableCell></TableRow>) : filtered.map(so => (
              <TableRow key={so.id} onClick={(e) => { if ((e.target as HTMLElement).closest('button, [role="menuitem"], a, input, [data-radix-popper-content-wrapper]')) return; window.open(`${SO_MODULE_URL}?so=${encodeURIComponent(so.id)}`, "_blank", "noopener"); }} className={`cursor-pointer group hover:bg-[#F0F7FF] ${density === "condensed" ? "[&>td]:py-1 [&>td]:pl-4 [&>td]:pr-2" : "[&>td]:py-2 [&>td]:pl-4 [&>td]:pr-2"}`}>
                <TableCell className="sticky left-0 z-10 bg-card group-hover:bg-[#F0F7FF]" style={{ width: CHECKBOX_W, minWidth: CHECKBOX_W, maxWidth: CHECKBOX_W, paddingLeft: 8, paddingRight: 0 }}><Checkbox checked={selectedRows.has(so.id)} onCheckedChange={() => setSelectedRows(p => { const n = new Set(p); if (n.has(so.id)) n.delete(so.id); else n.add(so.id); return n; })} onClick={(e) => e.stopPropagation()} /></TableCell>
                {visibleColumns.map(key => { const def = cDef(key); const w = getWidth(key); const isS = def.sticky === "left"; const isLS = key === lastStickyKey; const isD = draggingColumnKey === key; return (
                  <TableCell key={key} className={`${isS ? "sticky z-10 bg-card group-hover:bg-[#F0F7FF]" : ""} ${def.align === "right" ? "text-right tabular-nums" : ""}`} style={{ width: w, minWidth: w, maxWidth: w, overflow: "hidden", textOverflow: "ellipsis", ...(isS ? { left: stickyOffsets[key], ...(!isD && isLS ? { boxShadow: "inset -1px 0 0 0 rgba(0,0,0,0.08), 3px 0 6px -2px rgba(0,0,0,0.06)" } : {}) } : {}), ...(isD ? { backgroundColor: "rgba(10,119,255,0.035)" } : {}) }}>{renderCell(so, key)}</TableCell>
                ); })}
                <TableCell className="sticky right-0 bg-card group-hover:bg-[#F0F7FF] z-10 !pl-2 !pr-2" style={{ boxShadow: "inset 1px 0 0 0 rgba(0,0,0,0.08)" }}>
                  <DropdownMenu><DropdownMenuTrigger asChild onClick={(e) => e.stopPropagation()}><button className="inline-flex items-center justify-center h-8 w-8 rounded-md text-muted-foreground hover:bg-muted/60 hover:text-foreground transition-colors cursor-pointer"><MoreHorizontal className="w-4 h-4" /></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-[180px]" onClick={(e) => e.stopPropagation()}><DropdownMenuItem><Eye className="w-4 h-4 mr-2" /> View Details</DropdownMenuItem><DropdownMenuItem><Pencil className="w-4 h-4 mr-2" /> Edit</DropdownMenuItem><DropdownMenuItem><Copy className="w-4 h-4 mr-2" /> Duplicate</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem className="text-[#DC2626] focus:text-[#DC2626] focus:bg-[#FEF2F2]"><Trash2 className="w-4 h-4 mr-2" /> Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
      <div ref={ghostElRef} className="fixed top-0 left-0 z-[9999] pointer-events-none" style={{ opacity: draggingColumnKey ? 1 : 0 }}>{draggingColumnKey && <div className="bg-white/95 backdrop-blur-sm border border-[#0A77FF]/20 shadow-lg rounded-lg px-3 py-1.5 -translate-x-1/2 -translate-y-full" style={{ marginTop: -8 }}><span className="text-[12px] text-[#0A77FF]" style={{ fontWeight: 600 }}>{cDef(draggingColumnKey as ColKey)?.label}</span></div>}</div>
      <div className="flex items-center justify-center px-4 py-3 border-t border-border gap-3 shrink-0"><span className="text-sm text-muted-foreground">Records per page</span><span className="text-sm px-2 py-1 border border-border rounded-md" style={{ fontWeight: 500 }}>20</span><div className="flex items-center gap-1 ml-4"><Button variant="ghost" size="sm" className="h-8 w-8 p-0" disabled><ChevronsLeft className="w-4 h-4" /></Button><Button variant="ghost" size="sm" className="h-8 gap-1 text-sm text-muted-foreground" disabled><ChevronLeft className="w-3.5 h-3.5" /> Prev</Button><Button size="sm" className="h-8 w-8 p-0 text-sm bg-primary text-primary-foreground">1</Button><Button variant="ghost" size="sm" className="h-8 gap-1 text-sm text-muted-foreground" disabled>Next <ChevronRight className="w-3.5 h-3.5" /></Button><Button variant="ghost" size="sm" className="h-8 w-8 p-0" disabled><ChevronsRight className="w-4 h-4" /></Button></div></div>
      </div>
      <ColumnSelector columns={COLUMN_DEFS} columnOrder={columnOrder} columnVisibility={columnVisibility} onColumnOrderChange={(o) => setColumnOrder(o as ColKey[])} onColumnVisibilityChange={setColumnVisibility} lockedColumns={["so_no"]} open={columnDrawerOpen} onOpenChange={setColumnDrawerOpen} />
    </div>
  );
}
